# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_gripper_controller:
      type: position_controllers/GripperActionController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
    command_interfaces:
      []
    state_interfaces:
      []
left_gripper_controller:
  ros__parameters:
    joint: left_robotiq_85_left_knuckle_joint
right_arm_controller:
  ros__parameters:
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
    command_interfaces:
      []
    state_interfaces:
      []
right_gripper_controller:
  ros__parameters:
    joint: right_robotiq_85_left_knuckle_joint